In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [86]:
#game (class)
class Soccer:
  def __init__(self):
    self.player_a_pos = [0,2]
    self.player_b_pos = [0,1]
    self.player_a_ball = False
    self.grid = np.zeros((2,4))
    self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 1
    self.grid[self.player_b_pos[0],self.player_b_pos[1]] = -1
    #reward represents reward for player a, blayer b is just *-1
    self.reward = 0

  def move(self, player, action):
    """move the player somewhere, player 1 is a, player 2 is b. Actions 0=N, 1=S, 2=E, 3=W, 4=Stick"""
    if player == 1:
      #player a moves
      if action == 0 and self.player_a_pos[0] != 0:
        print("action 0")
        player_a_pos_new = self.player_a_pos.copy()
        player_a_pos_new[0] = player_a_pos_new[0]-1
        if self.check_collision(player_a_pos_new,player):
          if self.player_a_ball:
            self.player_a_ball = False
        else:
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 0
          print(self.grid[self.player_a_pos[0],self.player_a_pos[1]])
          self.player_a_pos = player_a_pos_new
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 1
      if action == 1 and self.player_a_pos[0] != 1:
        
        player_a_pos_new = self.player_a_pos.copy()
        
        player_a_pos_new[0] = player_a_pos_new[0]+1
        
        if self.check_collision(player_a_pos_new,player):
          
          if self.player_a_ball:
            self.player_a_ball = False
            
        else:
          
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 0
          
          self.player_a_pos = player_a_pos_new
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 1
          
      if action == 2 and self.player_a_pos[1] != 3:
        print("action 2")
        player_a_pos_new = self.player_a_pos.copy()
        player_a_pos_new[1] = player_a_pos_new[1]+1
        if self.check_collision(player_a_pos_new,player):
          if self.player_a_ball:
            self.player_a_ball = False
        else:
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 0
          
          self.player_a_pos = player_a_pos_new
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 1
      if action == 3 and self.player_a_pos[1] != 0:
        print("action 3")
        player_a_pos_new = self.player_a_pos.copy()
        player_a_pos_new[1] = player_a_pos_new[1]-1
        if self.check_collision(player_a_pos_new,player):
          if self.player_a_ball:
            self.player_a_ball = False
        else:
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 0
          
          self.player_a_pos = player_a_pos_new
          self.grid[self.player_a_pos[0],self.player_a_pos[1]] = 1

    
    elif player == 2:
      #player b moves
      if action == 0 and self.player_b_pos[0] != 0:
        player_b_pos_new = self.player_b_pos.copy()
        player_b_pos_new[0] = player_b_pos_new[0]-1
        if self.check_collision(player_b_pos_new,player):
          if not self.player_a_ball:
            self.player_a_ball = True
        else:
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = 0
          
          self.player_b_pos = player_b_pos_new
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = -1
      elif action == 1 and self.player_b_pos[0] != 1:
        player_b_pos_new = self.player_b_pos.copy()
        player_b_pos_new[0] = player_b_pos_new[0]+1
        if self.check_collision(player_b_pos_new,player):
          if not self.player_a_ball:
            self.player_a_ball = True
        else:
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = 0
          
          self.player_b_pos = player_b_pos_new
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = -1
      elif action == 2 and self.player_b_pos[1] != 3:
        player_b_pos_new = self.player_b_pos.copy()
        player_b_pos_new[1] = player_b_pos_new[1]+1
        if self.check_collision(player_b_pos_new,player):
          if not self.player_a_ball:
            self.player_a_ball = True
        else:
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = 0
          
          self.player_b_pos = player_b_pos_new
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = -1
          
      elif action == 3 and self.player_b_pos[1] != 0:
        player_b_pos_new = self.player_b_pos.copy()
        player_b_pos_new[1] = player_b_pos_new[1]-1
        if self.check_collision(player_b_pos_new,player):
          if not self.player_a_ball:
            self.player_a_ball = True
        else:
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = 0
          
          self.player_b_pos = player_b_pos_new
          self.grid[self.player_b_pos[0],self.player_b_pos[1]] = -1
    
    return self.player_a_pos, self.player_b_pos, self.player_a_ball, self.check_game_over()
  

  def check_collision(self, new_pos, player):
    """check if the movement causes a collision"""
    if player == 1:

      if new_pos == self.player_b_pos:
        return True
      else:
        return False
    elif player == 2:
      if new_pos == self.player_a_pos:
        return True
      else:
        return False
    



  def check_game_over(self):
    """check if a goal was scored"""
    #player a scored
    if ((self.grid[:,0] == 1).any() and self.player_a_ball) or ((self.grid[:,3] == -1).any() and not self.player_a_ball):
      self.reward = 100
      return self.reward
    #player b scored
    elif ((self.grid[:,0] == -1).any() and not self.player_a_ball) or ((self.grid[:,3] == 1).any() and self.player_a_ball):
      self.reward = -100
      return self.reward
    else:
      return 0



  

In [ ]:
env = Soccer()
print(env.grid)
env.move(2,2)
env.move(1,1)
env.move(1,3)
env.move(1,3)


[[ 0. -1.  1.  0.]
 [ 0.  0.  0.  0.]]
action 3
action 3


(array([[ 0., -1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.]]), True, 100)

In [ ]:
#correlated q

In [ ]:
#foe q

In [82]:
#friend q
print(8*7*2)

112


In [85]:
#q-learning
#number of a pos = 8, number of b pos in each a pos = 8 (cant occupy same square),  2 (have the ball or dont), 5 actions
player_a_Q = np.zeros((8,8,2,5))
player_b_Q = np.zeros((8,8,2,5))
epsilon = .99
error = np.zeros((10**6))

def take_action_a(apos,bpos,ball):
    """take an action, greedy epsilon"""
    if np.random.random() < epsilon:
      return np.random.randint(0,5)
    else:
      return np.argmax(self.player_a_Q[apos,bpos,ball])
step_num = 0
while step_num < (10**6):
  game = Soccer()
  while True:
    #state info
    a_pos = game.player_a_pos[0]*4 + game.player_a_pos[1]
    b_pos = game.player_b_pos[0]*4 + game.player_b_pos[1]
    if game.player_a_ball:
      a_ball = 1
    else:
      a_ball = 0
    #generate an action

    #new state randomly determine who moves first
    if np.random.random() < .5:
      new_a_pos, new_b_pos, new_a_ball, rewarda = game.move(1,action1)
      new_a_pos, new_b_pos, new_a_ball, rewardb = game.move(2,action2)
    else:
      new_a_pos, new_b_pos, new_a_ball, rewarda = game.move(1,action1)
      new_a_pos, new_b_pos, new_a_ball, rewardb = game.move(2,action2)
