In [ ]:
import gym
import numpy as np
import time, pickle, os
import math

array = np.array(list("SFFHFFHFG"))
gamma = 0.95
lr_rate = 0.28
epsilon = 0.18
total_episodes = 28392
seedval = 679387

amap = np.reshape(array,(3,3))
env = gym.make("FrozenLake-v0", desc=amap).unwrapped









Q = np.zeros((env.observation_space.n, env.action_space.n))
#Q = np.full((env.observation_space.n, env.action_space.n),.5)
#Q[4]=[0,0,0,0]
#Q[15]=[0,0,0,0]
randomcount1 = 0
randomcount2 = 0

def choose_action(state):
  action=0
  global randomcount1
  global randomcount2
  randomcount1 += 1
  if np.random.random() < epsilon:
    action = np.random.randint(0,4)
    
  else:
    action = np.argmax(Q[state, :])
  #print(action)
  return action

def learn(state, state2, reward, action, action2):
	predict = Q[state, action]
	target = reward + gamma * Q[state2, action2]
	Q[state, action] = Q[state, action] + lr_rate * (target - predict)

# Start


rewards=0
env.seed(seedval)
np.random.seed(seedval)
for episode in range(total_episodes):
  t = 0
  state = env.reset()
  action = choose_action(state)
  

    
  while True:
    #env.render()
    #print("hello")

    state2, reward, done, info = env.step(action)

    action2 = choose_action(state2)

    learn(state, state2, reward, action, action2)

    state = state2
    action = action2

    t += 1
    rewards+=1

    if done:
      break
  # epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode) 
  # os.system('clear')
		#time.sleep(0.1)
print(randomcount1)
print(randomcount2)
print ("Score over time: ", rewards/total_episodes)
print(Q)
directions = np.argmax(Q, axis=1)

truedirections = ""
for x in directions:
  if x == 0:
    truedirections = truedirections + "<"
  elif x == 1:
    truedirections = truedirections +  "v"
  elif x == 2:
    truedirections = truedirections +  ">"
  elif x == 3:
    truedirections = truedirections +  "^"
  
print(truedirections)
#LEFT = 0
#DOWN = 1
#RIGHT = 2
#UP = 3

with open("frozenLake_qTable_sarsa.pkl", 'wb') as f:
	pickle.dump(Q, f)

367527
0
Score over time:  11.94473795435334
[[0.28391435 0.34751067 0.18810607 0.50850809]
 [0.4844263  0.56356414 0.65805783 0.52092919]
 [0.58558793 0.68180198 0.75860394 0.5447635 ]
 [0.         0.         0.         0.        ]
 [0.28160909 0.49381102 0.79843586 0.48162295]
 [0.67066424 0.882724   0.73111634 0.61880155]
 [0.         0.         0.         0.        ]
 [0.18376372 0.70309841 0.96704602 0.57442859]
 [0.         0.         0.         0.        ]]
^>><>v<><
